# Generated by .github/workflows/update-release-info.yml — do not hand-edit.
# `version` and each asset's `sha256` are regenerated automatically whenever
# a new upstream orpos/kaledis release is published; url/sha256 always refer
# to that upstream release's binaries.
{
  version = "4.0.1";
  assets = {
    x86_64-linux = {
      url = "https://github.com/orpos/kaledis/releases/download/v4.0.1/kaledis-4.0.1-linux-x86_64.tar.gz";
      sha256 = "sha256-11tJMambtpkPAr6Rz9h15CQKQssl52ohu/evPZLoJ3o=";
    };
    x86_64-darwin = {
      url = "https://github.com/orpos/kaledis/releases/download/v4.0.1/kaledis-4.0.1-macos-x86_64.tar.gz";
      sha256 = "sha256-jXBlpvCZpwruiBdHiuUFRb1aplwoCE/2cGS9iky8N80=";
    };
    aarch64-darwin = {
      url = "https://github.com/orpos/kaledis/releases/download/v4.0.1/kaledis-4.0.1-macos-aarch64.tar.gz";
      sha256 = "sha256-TuRDmTkPPkYt8OS53N7NtcIP5V5NlISShlKefcBSN/I=";
    };
  };
}
